#!/bin/bash

rsync -rv --size-only /Users/leftbrained/Music/iTunes/iTunes\ Media/Audiobooks/* /Volumes/MeejaBackup/S3/Audio
rsync -rv --size-only /Users/leftbrained/Music/iTunes/iTunes\ Media/Podcasts/* /Volumes/MeejaBackup/S3/Podcasts
#rsync -rv --size-only /Users/leftbrained/Music/iTunes/iTunes\ Media/Books/* /Volumes/Meeja/Backup/Books
rsync -rv --size-only /Users/leftbrained/Pictures/iPhoto\ Library.photolibrary/Masters /Volumes/MeejaBackup/NotS3/Pictures

