#!/usr/bin/env ruby

if ARGV.empty?
 puts "pd target_device <args> - run <args> and then send a message via Prowl letting me know that the job has finished"
 exit;
end

device_name = ARGV.shift 
command = ARGV.join(" ")[0..50]

system command 
system "prowl '#{command}' -t #{device_name} -a 'Task Complete'"
