#!/usr/bin/env ruby

if ARGV.empty?
 puts "pd target_device <args> - run <args> and then send a message via Prowl letting me know that the job has finished"
 exit;
end

device_name = ARGV.shift 
command = ARGV.join(" ")[0..50]

system command 
output_code = $?.to_i
outcome = output_code.zero? ? "Task Complete" : "Task Failed [#{output_code}]"
system "prowl '#{command}' -t #{device_name} -a '#{outcome}'"
